/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package disease_welcome;

import com.sun.org.apache.xalan.internal.lib.ExsltStrings;
import java.awt.Checkbox;
import java.awt.Component;
import java.io.*;
import java.sql.*;
import java.util.*;
import javax.swing.*;

public class rough extends javax.swing.JFrame {
  List checkboxes = new ArrayList();
  
 int i = 0;
    boolean stat= true;

    public rough() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(465, 406));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel1.setText("Make choice for your symptoms:");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 326, 25);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox1.setText("Headache");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(20, 43, 85, 25);

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox2.setText("Shortness of Breath ");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(20, 71, 151, 25);

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox3.setText("Nosebleeds");
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(20, 99, 93, 25);

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox4.setText("Fatigue");
        getContentPane().add(jCheckBox4);
        jCheckBox4.setBounds(20, 127, 69, 25);

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox5.setText("Peeing more often and being thirstier");
        getContentPane().add(jCheckBox5);
        jCheckBox5.setBounds(20, 155, 251, 25);

        jCheckBox6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox6.setText("Dry mouth and itchy skin");
        getContentPane().add(jCheckBox6);
        jCheckBox6.setBounds(20, 183, 181, 25);

        jCheckBox7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox7.setText("Blurred vision");
        getContentPane().add(jCheckBox7);
        jCheckBox7.setBounds(20, 211, 107, 25);

        jCheckBox8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox8.setText("Unplanned weight loss");
        getContentPane().add(jCheckBox8);
        jCheckBox8.setBounds(20, 239, 161, 25);

        jCheckBox9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox9.setText("Nausea and vomiting");
        getContentPane().add(jCheckBox9);
        jCheckBox9.setBounds(20, 267, 153, 25);

        jCheckBox10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox10.setText("Hair Loss");
        getContentPane().add(jCheckBox10);
        jCheckBox10.setBounds(20, 323, 79, 25);

        jCheckBox11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox11.setText("Muscle and Joint Pains");
        jCheckBox11.setToolTipText("");
        getContentPane().add(jCheckBox11);
        jCheckBox11.setBounds(20, 295, 161, 25);

        jCheckBox12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox12.setText("Constipation");
        getContentPane().add(jCheckBox12);
        jCheckBox12.setBounds(284, 295, 101, 25);

        jCheckBox13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox13.setText("Neck Discomfort");
        getContentPane().add(jCheckBox13);
        jCheckBox13.setBounds(284, 323, 127, 25);

        jCheckBox14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox14.setText("Heavy Periods");
        getContentPane().add(jCheckBox14);
        jCheckBox14.setBounds(284, 43, 113, 25);

        jCheckBox15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox15.setText("High Cholesterol");
        getContentPane().add(jCheckBox15);
        jCheckBox15.setBounds(284, 71, 123, 25);

        jCheckBox16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox16.setText("Depression");
        getContentPane().add(jCheckBox16);
        jCheckBox16.setBounds(284, 99, 93, 25);

        jCheckBox18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox18.setText("Fever");
        getContentPane().add(jCheckBox18);
        jCheckBox18.setBounds(284, 127, 59, 25);

        jCheckBox19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox19.setText("Rash");
        getContentPane().add(jCheckBox19);
        jCheckBox19.setBounds(284, 155, 55, 25);

        jCheckBox20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox20.setText("Sore throat");
        getContentPane().add(jCheckBox20);
        jCheckBox20.setBounds(284, 183, 95, 25);

        jCheckBox21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox21.setText("Mouth or genital ulcers");
        getContentPane().add(jCheckBox21);
        jCheckBox21.setBounds(284, 211, 163, 25);

        jCheckBox22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox22.setText("Night sweats ");
        jCheckBox22.setToolTipText("");
        getContentPane().add(jCheckBox22);
        jCheckBox22.setBounds(284, 239, 107, 25);

        jCheckBox23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox23.setText("Chills");
        getContentPane().add(jCheckBox23);
        jCheckBox23.setBounds(284, 267, 55, 25);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(171, 355, 113, 25);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        checkboxes.clear();
        
        if(jCheckBox1.isSelected())
        {
          checkboxes.add(jCheckBox1.getText());
        }
        if(jCheckBox2.isSelected())
        {
          checkboxes.add(jCheckBox2.getText());
        }
        if(jCheckBox3.isSelected())
        {
          checkboxes.add(jCheckBox3.getText());
        }
        if(jCheckBox4.isSelected())
        {
          checkboxes.add(jCheckBox4.getText());
        }
        if(jCheckBox5.isSelected())
        {
          checkboxes.add(jCheckBox5.getText());
        }
        if(jCheckBox6.isSelected())
        {
          checkboxes.add(jCheckBox6.getText());
        }
        if(jCheckBox7.isSelected())
        {
          checkboxes.add(jCheckBox7.getText());
        }
         if(jCheckBox8.isSelected())
        {
          checkboxes.add(jCheckBox8.getText());
        }
          if(jCheckBox9.isSelected())
        {
          checkboxes.add(jCheckBox9.getText());
        }
          if(jCheckBox10.isSelected())
        {
          checkboxes.add(jCheckBox10.getText());
        }
          if(jCheckBox11.isSelected())
        {
          checkboxes.add(jCheckBox11.getText());
        }
          if(jCheckBox12.isSelected())
        {
          checkboxes.add(jCheckBox12.getText());
        }
          if(jCheckBox13.isSelected())
        {
          checkboxes.add(jCheckBox13.getText());
        }
          if(jCheckBox14.isSelected())
        {
          checkboxes.add(jCheckBox14.getText());
        }
          if(jCheckBox15.isSelected())
        {
          checkboxes.add(jCheckBox15.getText());
        }
          if(jCheckBox16.isSelected())
        {  checkboxes.add(jCheckBox16.getText());
        }
                
          if(jCheckBox18.isSelected())
        {
          checkboxes.add(jCheckBox18.getText());
        }
          if(jCheckBox19.isSelected())
        {
          checkboxes.add(jCheckBox19.getText());
        }
          if(jCheckBox20.isSelected())
        {
          checkboxes.add(jCheckBox20.getText());
        }
         if(jCheckBox21.isSelected())
        {
          checkboxes.add(jCheckBox21.getText());
        }
         if(jCheckBox22.isSelected())
        {
          checkboxes.add(jCheckBox22.getText());
        }
         if(jCheckBox23.isSelected())
        {
          checkboxes.add(jCheckBox23.getText());
        }
                   
      try{
        
    connect ob = new connect();
    Connection con = ob.conn();
    
        
     PreparedStatement ps = con.prepareStatement("select * from dis");
     ResultSet rs = ps.executeQuery();
       
    while(rs.next())
    { String str = null;
     str = rs.getString("Symptoms");
     StringTokenizer st = new StringTokenizer(str,",");
     i=0;
     while (st.hasMoreElements() && i < checkboxes.size())
     { 
	if(checkboxes.get(i).equals(st.nextElement()))
        { stat = false;           
          super.dispose();
        JOptionPane.showMessageDialog(this,"You may be suffering from: " + rs.getString("Disease"));
       break;
         }
         i++;
     }
         
     
    //for(int i = 0; i < checkboxes.size(); i++){}
    //retval = str.split("\\,");
   // for(String content: retval)){
   //System.out.print(retval);
           
           // System.out.println(r.checkboxes);
        
        
    //  if(retval.equals(checkboxes.get(i)) );
    //{
     // super.dispose();
     // new View().setVisible(true);
    //}
        
    
    
    
    //for(int i = 0; i < checkboxes.size(); i++) {
      //      if(checkboxes.get(i).equals());
    }} 
    catch(Exception e)
    { e.printStackTrace();
    }   
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rough.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rough.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rough.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rough.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rough().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
